# Build the lotus-node image
      - name: Build lotus-node Docker image
        uses: docker/build-push-action@v4
        if: github.event_name != 'pull_request'
        with:
          context: .
          file: dockerfiles/Dockerfile.lotus-node
          push: false  # Don't push to registry yet
          load: true   # Load into local Docker daemon
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LC }}/lotus-node:sha-${{ github.sha }}
            ghcr.io/${{ env.REPO_OWNER_LC }}/lotus-node:${{ inputs.version }}
            ghcr.io/${{ env.REPO_OWNER_LC }}/lotus-node:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          outputs: type=docker
      
      # Extract binary with improved method
      - name: Extract binary from Docker image
        if: github.event_name != 'pull_request'
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          mkdir -p ./artifacts
          
          echo "Extracting from local Docker image..."
          # Extract from the local Docker image
          CONTAINER_ID=$(docker create ghcr.io/${{ env.REPO_OWNER_LC }}/lotus-node:sha-${{ github.sha }})
          docker cp $CONTAINER_ID:/opt/lotus/bin/lotus-node ./artifacts/
          docker rm -v $CONTAINER_ID
          echo "Successfully extracted binary from Docker image"
          
          # Verify file exists and has content
          FILE_SIZE=$(stat -c%s "./artifacts/lotus-node" 2>/dev/null || echo "0")
          echo "Binary file size: ${FILE_SIZE} bytes"
          if [ "$FILE_SIZE" -lt 1000 ]; then
            echo "WARNING: Extracted binary is very small (${FILE_SIZE} bytes)!"
          fi
      
      # Now push to registry after successful extraction
      - name: Push Docker images to registry
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: dockerfiles/Dockerfile.lotus-node
          push: true  # Now we push to registry
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LC }}/lotus-node:sha-${{ github.sha }}
            ghcr.io/${{ env.REPO_OWNER_LC }}/lotus-node:${{ inputs.version }}
            ghcr.io/${{ env.REPO_OWNER_LC }}/lotus-node:latest
          cache-from: type=local,src=/tmp/.buildx-cache
      
      # Move the cache
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache || true 