name: Telegram Notifications

on:
  push:
    branches: [master]
  pull_request:
    types: [closed]

jobs:
  notify:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    uses: LotusiaStewardship/actions/.github/workflows/notify-telegram.yml@master
    with:
      repo: ${{ github.repository }}
    secrets:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
